=== Taeradan/JenericAHP/GenericAHP/src/org/taeradan/ahp/conf/ahp_conf.dtd
<?xml version='1.0' encoding='UTF-8'?>

	<!--
	    TODO define vocabulary identification
	    PUBLIC ID: -//vendor//vocabulary//EN
	    SYSTEM ID: http://server/path/ahp_conf.dtd

	--><!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE root SYSTEM "ahp_conf.dtd">

    <root>
    ...
    </root>
-->

	<!--- The root element of the XML document is the root element of the AHP tree.
	It must contain a name, a preference matrix and an array of criterias elements. -->
	<!ELEMENT root (name,prefmatrix,criteria*)>

	<!--- The name of the AHP tree (or the goal of this AHP instance). -->
	<!ELEMENT name (#PCDATA)>

	<!--- The preference matrix is a square matrix that establish preferences between each criterias in the root or each indicators of a given criterion.
	Contains rows.
	It must have as much rows and colums than the number of elements compared. -->
	<!ELEMENT prefmatrix (row)*>

	<!--- A row of the preference matrix, contains elements. -->
	<!ELEMENT row (elt)*>

	<!--- An element of the preference matrix, contains the value of a criterion/criterion or indicator/indicator preference. -->
	<!ELEMENT elt EMPTY>
	<!ATTLIST elt
		value CDATA #REQUIRED
		>

	<!--- A criterion contains a name, a preference matrix and an array of indicators. -->
	<!ELEMENT criteria (name,prefmatrix,indicator*)>
	<!ATTLIST criteria
		id CDATA #REQUIRED
		>

	<!--- An indicator contains a name, and is it has to be minimized or maximized. -->
	<!ELEMENT indicator (name,(minimize|maximize))>
	<!ATTLIST indicator
		id CDATA #REQUIRED
		>

	<!--- These elements are used to determine if an indicator has to be maximized or minimized. -->
	<!ELEMENT minimize EMPTY>
	<!ELEMENT maximize EMPTY>

=== Taeradan/JenericAHP/GenericAHP/src/org/taeradan/ahp/conf/empty_ahp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "ahp_conf.dtd">

<!--
	Document   : empty_ahp.xml
	Created on : 28 janvier 2013, 01:41
	Author     : Jean-Pierre PRUNARET
	Description:
		This document is the configuration file of the org.taeradan.ahp package, a new generic Java implementation of the AHP algorithm.
		For syntax information, just have a look at the ahp_conf.dtd file.
-->

<root>
	<name>Main goal</name>
	<prefmatrix>
		<row>
			<elt value="1"/>
			<elt value="1"/>
			<elt value="1"/>
		</row>
		<row>
			<elt value="1"/>
			<elt value="1"/>
			<elt value="1"/>
		</row>
		<row>
			<elt value="1"/>
			<elt value="1"/>
			<elt value="1"/>
		</row>
	</prefmatrix>
	<criteria id="C1">
		<name>My 1st criterion</name>
		<prefmatrix>
			<row>
				<elt value="1"/>
				<elt value="1/3"/>
				<elt value="1/3"/>
			</row>
			<row>
				<elt value="3"/>
				<elt value="1"/>
				<elt value="1"/>
			</row>
			<row>
				<elt value="3"/>
				<elt value="1"/>
				<elt value="1"/>
			</row>
		</prefmatrix>
		<indicator id="I11">
			<name>Indicator 11 : blah blah</name>
			<maximize/>
		</indicator>
		<indicator id="I12">
			<name>Indicator 12 : blah blah</name>
			<maximize/>
		</indicator>
		<indicator id="I13">
			<name>Indicator 13 : blah blah</name>
			<maximize/>
		</indicator>
	</criteria>
	<criteria id="C2">
		<name>My 2nd criterion</name>
		<prefmatrix>
			<row>
				<elt value="1"/>
				<elt value="1"/>
			</row>
			<row>
				<elt value="1"/>
				<elt value="1"/>
			</row>
		</prefmatrix>
		<indicator id="I21">
			<name>Indicator 21 : blah blah</name>
			<maximize/>
		</indicator>
		<indicator id="I22">
			<name>Indicator 21 : blah blah</name>
			<maximize/>
		</indicator>
	</criteria>
	<criteria id="C3">
		<name>My 3rd criterion</name>
		<prefmatrix>
			<row>
				<elt value="1"/>
				<elt value="1"/>
			</row>
			<row>
				<elt value="1"/>
				<elt value="1"/>
			</row>
		</prefmatrix>
		<indicator id="I31">
			<name>Indicator 31 : blah blah</name>
			<minimize/>
		</indicator>
		<indicator id="I32">
			<name>Indicator 32 : blah blah</name>
			<minimize/>
		</indicator>
	</criteria>
</root>

=== Taeradan/JenericAHP/GenericAHP/src/org/taeradan/ahp/conf/controversial_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "ahp_conf.dtd">

<!--
	Document   : ahp_conf.xml
	Created on : 27 mars 2009, 15:05
	Author     : Yves Dubromelle
	Description:
		This document is the configuration file of the org.taeradan.ahp package, a new generic Java implementation of the AHP algorithm.
		For syntax information, just have a look at the ahp_conf.dtd file.
-->

<root>
	<name>Arbre de test de normalisation</name>
	<prefmatrix>
		<row><elt value="1"/></row>
	</prefmatrix>
	<criteria id="C">
		<name>Critère unique pour se concentrer sur les indicateurs</name>
		<prefmatrix>
			<row><elt value="1"/><elt value="1"/></row>
			<row><elt value="1"/><elt value="1"/></row>
		</prefmatrix>
		<indicator id="IT">
			<name>Indicateur témoin (valeur={1-1000})</name>
			<maximize/>
		</indicator>
		<indicator id="IV">
			<name>Indicateur variable</name>
			<maximize/>
		</indicator>
	</criteria>
</root>

=== Taeradan/JenericAHP/GenericAHP/src/org/taeradan/ahp/conf/ahp_conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "ahp_conf.dtd">

<!--
    Document   : ahp_conf.xml
    Created on : 27 mars 2009, 15:05
    Author     : Yves Dubromelle
    Description:
		This document is the configuration file of the org.taeradan.ahp package, a new generic Java implementation of the AHP algorithm.
		For syntax information, just have a look at the ahp_conf.dtd file.
-->

<root>
	<name>Choix d'un produit à traiter dans un WIP</name>
	<prefmatrix>
		<row><elt value="1"/><elt value="1/3"/><elt value="1/3"/><elt value="3"/><elt value="1"/></row>
		<row><elt value="3"/><elt value="1"/><elt value="1"/><elt value="9"/><elt value="3"/></row>
		<row><elt value="3"/><elt value="1"/><elt value="1"/><elt value="9"/><elt value="3"/></row>
		<row><elt value="1/3"/><elt value="1/9"/><elt value="1/9"/><elt value="1"/><elt value="1/3"/></row>
		<row><elt value="1"/><elt value="1/3"/><elt value="1/3"/><elt value="3"/><elt value="1"/></row>
	</prefmatrix>
	<criteria id="C1">
		<name>Type de produit</name>
		<prefmatrix>
			<row><elt value="1"/><elt value="1/3"/><elt value="1"/></row>
			<row><elt value="3"/><elt value="1"/><elt value="1"/></row>
			<row><elt value="1"/><elt value="1"/><elt value="1"/></row>
		</prefmatrix>
		<indicator id="C1I1">
			<name>Ligne en flow-shop ou en job-shop</name>
			<maximize/>
		</indicator>
		<indicator id="C1I2">
			<name>Produit principal ou de complément</name>
			<maximize/>
		</indicator>
		<indicator id="C1I3">
			<name>Produit pour assemblage ou de rechange</name>
			<maximize/>
		</indicator>
	</criteria>
	<criteria id="C2">
		<name>Progression du produit</name>
		<prefmatrix>
			<row><elt value="1"/><elt value="1"/></row>
			<row><elt value="1"/><elt value="1"/></row>
		</prefmatrix>
		<indicator id="C2I1">
			<name>Progression globale</name>
			<maximize/>
		</indicator>
		<indicator id="C2I2">
			<name>Progression locale</name>
			<maximize/>
		</indicator>
	</criteria>
	<criteria id="C3">
		<name>Marge restante</name>
		<prefmatrix>
			<row><elt value="1"/><elt value="1"/></row>
			<row><elt value="1"/><elt value="1"/></row>
		</prefmatrix>
		<indicator id="C3I1">
			<name>Marge restante</name>
			<minimize/>
		</indicator>
		<indicator id="C3I2">
			<name>Marge restante pondérée</name>
			<minimize/>
		</indicator>
	</criteria>
	<criteria id="C4">
		<name>Temps dans la file d'attente</name>
		<prefmatrix>
			<row><elt value="1"/></row>
		</prefmatrix>
		<indicator id="C4I1">
			<name>Temps d'attente</name>
			<maximize/>
		</indicator>
	</criteria>
	<criteria id="C5">
		<name>Charge de la ressource</name>
		<prefmatrix>
			<row><elt value="1"/></row>
		</prefmatrix>
		<indicator id="C5I1">
			<name>Charge de la ressource</name>
			<minimize/>
		</indicator>
	</criteria>
</root>
